version: '3.8'
networks:
  pulsar:
volumes:
  conf:
  data:

services:
  standalone:
    hostname: standalone
    image: apachepulsar/pulsar
    command: bin/pulsar standalone
    ports:
      - "6650:6650"
      - "8080:8080"
    networks:
      pulsar:
    volumes:
      - conf:/pulsar/conf
      - data:/pulsar/data
