---
apiVersion: v1
kind: Namespace
metadata: 
  name: group-0


---

apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits
  namespace: group-0
spec:
  limits:
    - default:
        cpu: 1000m
        memory: 2Gi
      max:
        cpu: 4000m
        memory: 8Gi
      type: Container

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: group-0
spec:
  hard: 
    limits.cpu: 4000m
    limits.memory: 8Gi