apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: schedule-delay-example
spec:
  schedule: '*/1 * * * *'
  historyLimit: 5
  concurrencyPolicy: 'Forbid'
  type: 'NetworkChaos'
  networkChaos:
    action: delay
    mode: all
    selector:
      namespaces:
        - group-0

    delay:
      latency: '10ms'
    duration: '10s'