---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-workload
  namespace: group-0
spec:
  template: 
    spec: 
      containers:
        - name: stress
          image: docker.io/alexeiled/stress-ng
          args: ["-c", "12", "-t", "60"]
      restartPolicy: Never

