apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-jobmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: jobmanager
  template:
    metadata:
      labels:
        app: flink
        component: jobmanager
    spec:
      containers:
      - name: jobmanager
        image: flink:1.19
        ports:
        - containerPort: 6123
        - containerPort: 8081
        - containerPort: 6124
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager
        args: ["jobmanager"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flink-taskmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flink
      component: taskmanager
  template:
    metadata:
      labels:
        app: flink
        component: taskmanager
    spec:
      containers:
      - name: taskmanager
        image: flink:1.19
        ports:
        - containerPort: 6121
        - containerPort: 6122
        env:
        - name: JOB_MANAGER_RPC_ADDRESS
          value: flink-jobmanager
        args: ["taskmanager"]
---
apiVersion: v1
kind: Service
metadata:
  name: flink-jobmanager
spec:
  type: ClusterIP
  ports:
  - name: rpc
    port: 6123
  - name: ui
    port: 8081
  - name: blob
    port: 6124
  selector:
    app: flink
    component: jobmanager
---
apiVersion: batch/v1
kind: Job
metadata:
  name: flink-wordcount-client
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: client
        image: flink:1.19
        command: ["/bin/sh", "-c"]
        args:
          - >
            sleep 10 && 
            flink run -m flink-jobmanager:8081 /opt/flink/examples/batch/WordCount.jar
