---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-workload
  namespace: group-1
spec:
  template: 
    spec: 
      containers:
        - name: client
          image: docker.io/jawadtahir/challengerclient:latest
          env:
          - name: API_TOKEN
            value: purwqyiryytfwseeqkghqdlrsxxdoauo
      restartPolicy: OnFailure

