---
apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - port: 9092
      name: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "1"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "1@kafka-0.kafka.default.svc.cluster.local:9093"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka:9092"
            - name: KAFKA_KRAFT_CLUSTER_ID
              value: "1d3cfcd1-8a2c-4a78-b62f-3b6f285fb2de"
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
          ports:
            - containerPort: 9092
            - containerPort: 9093
          volumeMounts:
            - name: kafka-data
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-producer
spec:
  restartPolicy: Never
  containers:
    - name: producer
      image: bitnami/kafka:latest
      command:
        - /bin/sh
        - -c
        - |
          sleep 20 && \
          kafka-topics.sh --create --topic test-topic --bootstrap-server kafka:9092 && \
          echo "hello-from-producer" | kafka-console-producer.sh --topic test-topic --bootstrap-server kafka:9092
---
apiVersion: v1
kind: Pod
metadata:
  name: kafka-consumer
spec:
  restartPolicy: Never
  containers:
    - name: consumer
      image: bitnami/kafka:latest
      command:
        - /bin/sh
        - -c
        - |
          sleep 30 && \
          kafka-console-consumer.sh --topic test-topic --bootstrap-server kafka:9092 --from-beginning --timeout-ms 10000
