@startuml
activate Participant
group Create a new Benchmark

Challenger <- Participant: CreateNewBenchmark(BenchmarkConfiguration)
activate Challenger
Challenger --> Participant: (Benchmark)
deactivate Challenger

end

group Calibrate Latency (optional)
Challenger <- Participant: CalibrateLatency(Benchmark)
activate Challenger
Challenger --> Participant: Ping

group Repeat multiple times
Challenger <- Participant: MeasureLatency(Ping)
activate Challenger
Challenger --> Participant: Ping
deactivate Challenger
end

Challenger <- Participant: EndMeasurement(Ping)
deactivate Challenger

deactivate Challenger
end

group Benchmark
Challenger <- Participant: StartBenchmark(Benchmark)
activate Challenger


group Repeat until finished
Challenger <- Participant: nextMessage(Benchmark)
activate Challenger
Challenger --> Participant: Payload

Challenger <- Participant: processed(Result)
Challenger --> Participant:
deactivate Challenger
end


Challenger <- Participant: EndBenchmark(Benchmark)

deactivate Challenger
end

@enduml