def menu(profile=False,
         recentchanges=False,
         documentation=False,
         system_status=False,
         benchmarks=False,
         leaderboard=False,
         testruns=False,
         scheduled_benchmarks=False,
         rawdata=False,
         feedback=False):
    return [
        ["Profile", "home", "/profile", profile],
        ["Recent changes", "layers", "/recentchanges", recentchanges],
        ["Documentation", "layers", "/documentation", documentation],
        ["Leaderboard", "layers", "/leaderboard", leaderboard],
        ["Benchmarks", "layers", "/benchmarks", benchmarks],
        ["System status", "layers", "/systemstatus", system_status],
        ["Test runs", "layers", "/testruns", testruns],
        ["Datasets", "rawdata", "/rawdata", rawdata],
        ["Feedback", "layers", "/feedback", feedback]]
