#! /bin/sh

echo printing current directory...
pwd

echo creating disk image...
qemu-img create -f qcow2 -b {os_img_path} -F qcow2 snapshot-focal-server_{team}_{vm_number}.qcow2 15G

echo creating seed image...
cloud-localds --network-config=./network_config.cfg seed.iso cloud_init.cfg

echo installing VM...
sudo virt-install --name vm_{team}_{vm_number} --vcpus 4 --memory 8192 --disk snapshot-focal-server_{team}_{vm_number}.qcow2,device=disk,bus=virtio --disk seed.iso,device=cdrom --os-type linux --os-variant ubuntu20.04  --graphics none --network bridge=br-provider,model=virtio,virtualport_type=openvswitch --import
