apiVersion: chaos-mesh.org/v1alpha1
kind: Schedule
metadata:
  name: delay-{deploy_id}
  namespace: {namespace}
spec:
  schedule: '*/{timer} * * * *'
  historyLimit: 5
  concurrencyPolicy: 'Forbid'
  type: 'NetworkChaos'
  networkChaos:
    action: delay
    mode: all
    selector:
      namespaces:
        - {namespace}

    delay:
      latency: '100ms'
    duration: '10s'