---
apiVersion: v1
kind: Namespace
metadata: 
  name: {namespace}

---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-limits-{namespace}
  namespace: {namespace}
spec:
  limits:
    - default:
        cpu: 1000m
        memory: 2Gi
      max:
        cpu: 4000m
        memory: 8Gi
      type: Container

---

apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota-{namespace}
  namespace: {namespace}
spec:
  hard: 
    limits.cpu: 4000m
    limits.memory: 8Gi